--script criação do banco de dados
create database locadorafilmes;

--Script de Criação
-- Tabela ENDERECO
CREATE TABLE ENDERECO (
    COD_END SERIAL PRIMARY KEY,
    LOGRADOURO VARCHAR(40),
    TIPO_LOG VARCHAR(40),
    COMPLEMENTO VARCHAR(20),
    CIDADE VARCHAR(60),
    UF CHAR(1),
    CEP CHAR(8),
    NUMERO VARCHAR(10),
    BAIRRO VARCHAR(60)
);

-- Tabela PROFISSAO
CREATE TABLE PROFISSAO (
    COD_PROF SERIAL PRIMARY KEY,
    NOME VARCHAR(60)
);

-- Tabela CLIENTE
CREATE TABLE CLIENTE (
    COD_CLI SERIAL PRIMARY KEY,
    CPF CHAR(11) NOT NULL,
    NOME VARCHAR(60),
    TELEFONE VARCHAR(15),
    COD_PROF INT,
    FOREIGN KEY (COD_PROF) REFERENCES PROFISSAO(COD_PROF)
);

-- Tabela DEPENDENTE
CREATE TABLE DEPENDENTE (
    COD_CLI INT NOT NULL,
    COD_DEP SERIAL PRIMARY KEY,
    PARENTESCO VARCHAR(20),
    FOREIGN KEY (COD_CLI) REFERENCES CLIENTE(COD_CLI)
);

-- Tabela CATEGORIA
CREATE TABLE CATEGORIA (
    COD_CAT SERIAL PRIMARY KEY,
    NOME VARCHAR(60),
    VALOR NUMERIC(15,2)
);

-- Tabela GENERO
CREATE TABLE GENERO (
    COD_GEN SERIAL PRIMARY KEY,
    NOME VARCHAR(60)
);

-- Tabela FILMES
CREATE TABLE FILMES (
    COD_FILME SERIAL PRIMARY KEY,
    TITULO_ORIGINAL VARCHAR(100),
    TITULO VARCHAR(100),
    QUANTIDADE INT,
    COD_CAT INT,
    COD_GEN INT,
    FOREIGN KEY (COD_CAT) REFERENCES CATEGORIA(COD_CAT),
    FOREIGN KEY (COD_GEN) REFERENCES GENERO(COD_GEN)
);

-- Tabela LOCACAO
CREATE TABLE LOCACAO (
    COD_LOC SERIAL PRIMARY KEY,
    DATA_LOC DATE,
    DESCONTO NUMERIC(15,2),
    MULTA NUMERIC(15,2),
    SUB_TOTAL NUMERIC(15,2),
    COD_CLI INT,
    FOREIGN KEY (COD_CLI) REFERENCES CLIENTE(COD_CLI)
);

-- Tabela LOCACAO_FILME
CREATE TABLE LOCACAO_FILME (
    COD_LOC INT NOT NULL,
    COD_FILME INT NOT NULL,
    QTD DIAS INT,
    DATA_DEVOL DATE,
    PRIMARY KEY (COD_LOC, COD_FILME),
    FOREIGN KEY (COD_LOC) REFERENCES LOCACAO(COD_LOC),
    FOREIGN KEY (COD_FILME) REFERENCES FILMES(COD_FILME)
);

-- Tabela ATOR
CREATE TABLE ATOR (
    COD_ATOR SERIAL PRIMARY KEY,
    NOME VARCHAR(60)
);

-- Tabela FILME_ATOR
CREATE TABLE FILME_ATOR (
    COD_ATOR INT NOT NULL,
    COD_FILME INT NOT NULL,
    ATOR CHAR(1),
    DIRETOR CHAR(1),
    PRIMARY KEY (COD_ATOR, COD_FILME),
    FOREIGN KEY (COD_ATOR) REFERENCES ATOR(COD_ATOR),
    FOREIGN KEY (COD_FILME) REFERENCES FILMES(COD_FILME)
);

-- Tabela CLI_ENDERECO
CREATE TABLE CLI_ENDERECO (
    COD_END INT NOT NULL,
    COD_CLI INT NOT NULL,
    PRIMARY KEY (COD_END, COD_CLI),
    FOREIGN KEY (COD_END) REFERENCES ENDERECO(COD_END),
    FOREIGN KEY (COD_CLI) REFERENCES CLIENTE(COD_CLI)
);



