-- Consultar todos os clientes
SELECT * FROM CLIENTE;

-- Consultar filmes por categoria
SELECT F.TITULO, C.NOME AS CATEGORIA 
FROM FILMES F
JOIN CATEGORIA C ON F.COD_CAT = C.COD_CAT;

-- Consultar locações de um cliente específico
SELECT L.DATA_LOC, F.TITULO 
FROM LOCACAO L
JOIN LOCACAO_FILME LF ON L.COD_LOC = LF.COD_LOC
JOIN FILMES F ON LF.COD_FILME = F.COD_FILME
WHERE L.COD_CLI = 1;

-- Consultar atores de um filme específico
SELECT A.NOME AS ATOR, F.TITULO
FROM ATOR A
JOIN FILME_ATOR FA ON A.COD_ATOR = FA.COD_ATOR
JOIN FILMES F ON FA.COD_FILME = F.COD_FILME
WHERE F.COD_FILME = 1;

-- Consultar endereço dos clientes
SELECT C.NOME, E.LOGRADOURO, E.NUMERO, E.CIDADE
FROM CLIENTE C
JOIN CLI_ENDERECO CE ON C.COD_CLI = CE.COD_CLI
JOIN ENDERECO E ON CE.COD_END = E.COD_END;
